general:

  #
  # List of enabled modles (and, optionally, their configuration)
  #

  modules:
    nodeca-core: on             # just enable and use default config options
    nodeca-translate:           #
      master-language: ru       # or provide overrides for config options
      enabled-languages:
        - en
        - ru

  #
  # Language configuration
  #

  languages:

    # *** Optional. Default application language
    # Default: en
    default: ru

    # *** Optional. List of enabled languages
    # Default: [en]
    enabled:
      - en
      - ru

  #
  # Themes configuration
  #

  themes:

    # Themes whitelist/blacklist
    #
    # If both `enabled` and `disabled` specified, `disabled` has ho effect.

    # *** Optional. Themes whitelist.
    # Only these themes will be enabled (if specified)
    # Default: all installed themes
    enabled:                    
      - red-hot-moon            
      - deep-purple             

    # *** Optional. Themes blacklist.
    # These themes will be disabled (if specified)
    # Default: none
    disabled:                   
      - yellow-submarine        

## PER-ENVIRONMENT CONFIGS ###################################################

production:
  listen:
    host: nodeca.org
    port: 80

development:
  listen:
    host: 127.0.0.1
    port: 8000

# vim:ft=yaml:ts=2:sw=2
