general:
  title: 'Nodeca'
  modules:
    nodeca-core:
      mount: '/'
    nodeca-translate:
      mount: '/translate'
## PER-ENVIRONMENT CONFIGS ###################################################
production:
  listen:
    host: nodeca.org
    port: 80
development:
  listen:
    host: nodeca.org
    port: 8000
